export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  CONFLICT: 'Conflict',
  NOT_FOUND: 'Not found',
  TOO_MANY_REQUESTS: 'Too many requests',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  UNAUTHORIZED: 'Unauthorized',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  USER_NOT_FOUND: 'User not found',
  ROUTE_NOT_FOUND: 'Route not found',
  REQUEST_TIMEOUT: 'Request timeout',
  FORBIDDEN: 'Forbidden',
  NOT_AUTHORIZED_ADMIN: 'Not authorized to the admin panel',
  USER_NOT_IN_THE_ADMIN: 'User is not an employee of the admin panel',
  USER_EMAIL_ALREADY_EXISTS:
    'Another user is already registered on the system with the same email address',
  ACTION_NOT_PERMITTED: 'Action not permitted',
  INVALID_COUNTRIES: 'Invalid countries',
  API_KEY_INVALID: 'API Key is invalid',
  SECRET_KEY_UNDEFINED: 'Secret Key is undefined',
};
